#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
# Get application directory
application=$(getApplication)

# Create meshes
runApplication -s fluid    blockMesh -region fluid


runApplication -s fluid    checkMesh -region fluid

# Create dummy files for post-processing
paraFoam -touch -region fluid

#------------------------------------------------------------------------------
