#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo
echo "creating files for paraview post-processing"
paraFoam -touchAll
echo

# Decompose
runApplication decomposePar -allRegions

# Run
runParallel tpcMultiRegionFoam_CUT

# Reconstruct
runApplication reconstructPar -allRegions
